name:                tmt
version:             0.1.0.0
github:              "benclifford/tmt"
license:             GPL-2
author:              "Ben Clifford"
maintainer:          "benc@hawaga.org.uk"
copyright:           "2018 Ben Clifford"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Temporary Merge Tool
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         tmt helps you make temporary git merges of several
   features branches, allowing you to cleanly develop several features
   at once.
   Please see the README on GitHub at <https://github.com/benclifford/tmt#readme>

dependencies:
- base >= 4.7 && < 5
- process
- text

library:
  source-dirs: src

executables:
  tmt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fPIC
    ld-options:
    - -static
    dependencies:
    - tmt

tests:
  tmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tmt
